apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-app-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: backstage-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: backstage_application/app/secrets
        property: jwt_secret
    - secretKey: stripe-secret-key
      remoteRef:
        key: backstage_application/app/secrets
        property: stripe_secret_key