apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-db-credentials
  namespace: default
spec:
  refreshInterval: 1h  
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: backstage-db-credentials   
    creationPolicy: Owner             
  data:
    - secretKey: host
      remoteRef:
        key: bs_applications/rds/credentials
        property: host
    - secretKey: username
      remoteRef:
        key: bs_applications/rds/credentials
        property: username
    - secretKey: password
      remoteRef:
        key: bs_applications/rds/credentials
        property: password
    - secretKey: dbname
      remoteRef:
        key: bs_applications/rds/credentials
        property: dbname